import {
  Generated,
  ColumnType,
  CamelCasePlugin,
  Kysely,
  PostgresDialect,
} from "kysely";
import { createKysely } from "@vercel/postgres-kysely";
import { Pool } from "pg";

interface Guests {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  name: string;
  cpfCnpj?: string;
  email?: string;
  phone?: string;
  instagramUserId?: string;
  isGoing: boolean;
  numberOfPeople?: number;
  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `createdAt` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  createdAt: ColumnType<Date, string | undefined, never>;
}

interface GuestsPresents {
  id: Generated<number>;
  guestId: number;
  message: string;
}

// Keys of this interface are table names.
export interface Database {
  guests: Guests;
  guests_presents: GuestsPresents;
}

function getKyselyInstance() {
  if (process.env.NODE_ENV === "development") {
    return new Kysely<Database>({
      dialect: new PostgresDialect({
        pool: new Pool({
          connectionString: process.env.POSTGRES_URL,
        }),
      }),
      plugins: [new CamelCasePlugin()],
    });
  } else {
    return createKysely<Database>(undefined, {
      plugins: [new CamelCasePlugin()],
    });
  }
}

export const db = getKyselyInstance();
export { sql } from "kysely";
